# <%= project %>

Generated by [CreactJS App Generator](https://github.com/hrberto/generator-reactjs-app) by [Helder Burato Berto](https://github.com/hrberto).

<%= description %>

## Requirements

* [NodeJS](https://nodejs.org/en/);
* [Yarn](https://yarnpkg.com/en/).

## Installation

* Run yarn to install required packages:
```bash
$ yarn install
```

## Usage

* Development:
```bash
$ yarn start
```

* Production
```bash
$ yarn run build
```

## Contributing

Please read [CONTRIBUTING.md](CONTRIBUTING.md) for details on our code of conduct, and the process for submitting pull requests to us.

## Changelog

This project adheres to [Semantic Versioning](https://semver.org/). Every release, along with the migration instructions, is documented on the Github [Releases](https://github.com/<%= github %>/<%= project %>/releases) page.

## Bugs and Sugestions

Report bugs or do suggestions using the [issues](https://github.com/<%= github %>/<%= project %>/issues).

## Author

[<%= author %>](https://github.com/<%= github %>)

## License

[MIT License](LICENSE)
